<?php
// $Id: freelinking_prepopulate.install,v 1.1.2.2 2009/11/19 07:38:54 grayside Exp $
/**
 * freelinking_prepopulate.install
 *
 * @file
 * Warns of specific Freelinking version compatibility.
 */

/**
 * Implementation of hook_enable().
 */
function freelinking_prepopulate_enable() {
  drupal_set_message(
    t('Freelinking Prepopulate provides plugins to the 3.x line of Freelinking.')
  );
}
