<?php

/**
 * Implementation of hook_uninstall().
 */
function casetracker_basic_uninstall() {
  db_query("DELETE FROM {node} WHERE type = 'casetracker_basic_project'");
  db_query("DELETE FROM {node} WHERE type = 'casetracker_basic_case'");
  db_query("DELETE FROM {node_type} WHERE type = 'casetracker_basic_project'");
  db_query("DELETE FROM {node_type} WHERE type = 'casetracker_basic_case'");
}